### ISSUE TITLE
[Blocks.EMBEDDED_ASSET] not working for images

### ISSUE THREAD

**Issue by codeithuman** [connor-baer/rich-text-to-jsx#1]
[Blocks.EMBEDDED_ASSET] not working for images. 

I think it has to do with https://github.com/connor-baer/rich-text-to-jsx/blob/5096c387e60b900bb6e17468796c26a02feb0fc5/src/rich-text-to-jsx.js#L118. 

My node structure does not match this pattern, but looks like the following. It is an image asset uploaded to a rich text field:

![2019-01-31_16-40-36](https://user-images.githubusercontent.com/3494509/52095282-4d50fd00-2577-11e9-9a5c-ec54b0574d17.jpg)

My goal is to pull the `id` (`contentful_id`) out of `data.target.sys` and then use <StaticQuery /> to query for that image and produce a fluid image for `gatsby-image`.

**Comment by connor-baer** [comment]
Hi @codeithuman! Thanks for opening an issue. I [struggled a bit](https://github.com/connor-baer/rich-text-to-jsx/blob/f9539dbe7086063ab5f394958abe304e5abd5458/src/rich-text-to-jsx.spec.js#L74-L98) to find a good, flexible solution for embedded assets and entries. Assets are particularly tricky since they don't have a content type and the mime type seems overly specific (e.g. you probably want to use the same component for `image/jpg` and `image/png`). 

I've finally found a compromise that I'm happy with: for assets, you can now define custom components by [mime type group](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/filtering-assets-by-mime-type) — that's the first part of the mime type, e.g. `image`. I've just released this change as `2.0.0` (this is a breaking change). 

Have a look at the [updated docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/filtering-assets-by-mime-type) and let me know what you think!

**Comment by codeithuman** [comment]
Wonderful, thank you @connor-baer! I'll be able to take a look before the end of the week and let you know. Again, I appreciate your time on this.

**Comment by connor-baer** [comment]
I've also added default components for image, video, and audio assets. Published as 2.1.0.

**Comment by kylefraser** [comment]
@connor-baer @codeithuman have either of you been able to test this and confirm that it's working? 

I'm getting a:

`Node type is invalid` red line error.

It looks like there is no `nodeType` in the `content` array on the `embedded-asset-block` in my query and thus it's failing.

My graphQL query looks like this

```
    body {
      nodeType
      content {
        nodeType
        data {
          target {
            sys {
              id
            }
          }
        }
        content {     
          value
          nodeType
        }
      }
    }
```

And the results looks like this:

```
...
{
  "nodeType": "embedded-asset-block",
    "data": {
      "target": {
        "sys": {
          "id": "c5cTwlejTau9t8MRbUNEze"
         }
       }
    },
  "content": []
},
{
  "nodeType": "heading-2",
    "data": {
      "target": null
       },
   "content": [
     {
      "value": "Test header field",
      "nodeType": "text"
     }
   ]
},
...
```

I believe the error is stemming from that empty `content` array and that it's looking for a `nodeType` within that.

Any help would be greatly appreciated. Everything else is working fine. Thanks.

**Comment by codeithuman** [comment]
Kyle, I tried it real quick and have a similar error. Unfortunately I
haven’t had time to look into it further and still using the have solution
in the fork I made.

I will be revisiting this in the weeks to come as I’m planning to use
Contentful + Gatsby on additional projects in the future.

**Comment by connor-baer** [comment]
@kylefraser For assets, I use the [mime type group](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/filtering-assets-by-mime-type) which is [extracted from the asset's mime type](https://github.com/connor-baer/rich-text-to-jsx/blob/master/src/rich-text-to-jsx.js#L169). 

The mime type is not part of the `content`, but the `target` property, specifically at `target.fields.file.contentType`. 

Could you please try with this query? 

```
...
body {
      nodeType
      content {
        nodeType
        data {
          target {
            sys {
              id
            }
            fields {
              file {
                contentType
              }
            }
          }
        }
        content {     
          value
          nodeType
		  data {
            uri
          }
        }
      }
    }
...
```

**Comment by kylefraser** [comment]
@connor-baer hmm i'm unable to even query `fields` on `target`, it doesn't show up.

here is my whole query for references:

```
query GuideBySlug($slug: String!) {
  contentfulResource(slug: {eq: $slug}) {
    id
    title
    subtitle
    body {
      nodeType      
      content {
        nodeType
        data {          
          target {            
            sys {
              id
            }            
          }          
        }
        content {     
          value
          nodeType
          data {
            uri
          }
        }
      }
    }
    resourceImage {
      fluid(quality: 95, maxWidth: 800) {
        src
      }
    }
    type
  }
}
```

**Comment by connor-baer** [comment]
Yeah, `rich-text-to-jsx` requires a specific content structure: entry and asset links need to be resolved and the content localized. I'll add a note about this to the README. 

If you're unable to adapt your content structure, I'd recommend looking at the official [`rich-text-react-renderer`](https://github.com/contentful/rich-text/tree/master/packages/rich-text-react-renderer) package. I collaborated on it with another developer after realizing that the limitations of this approach.

**Comment by kylefraser** [comment]
Thank you all for the feedback. @connor-baer we were able to get everything working with the `rich-text-react-renderer`, thanks a bunch of pointing me in the right direction!
