### ISSUE TITLE
Parse RTF string to JSX

### ISSUE THREAD

**Issue by drailanjohn** [connor-baer/rich-text-to-jsx#16]
## Summarize the question

Will it work for a rtf string for example like this? `{\\rtf1\\ansi\\b hi there\\b0}`

Because I tried to do it like this: 

`
const convertToPlain = rtf => {
    let plain = richTextToJsx(rtf);
    return plain;
  };
`

The output is null. 

## Context

Im trying to parse the rtf string into a jsx/html format. I expect the output to be like this 
`<p><strong>hi there</strong></p>`

## Specifications

* Version:
* Browser:
* OS:

**Comment by connor-baer** [comment]
Hi @drailanjohn, this package parses [Contentful rich text](https://www.contentful.com/developers/docs/concepts/rich-text/) which is in the format of a JSON AST, never a string. It looks like you're trying to parse a different kind of rich text which won't work with this package.

**Comment by daktap** [comment]
Hi !  Did u know how to convert this format "{\\rtf1\\ansi\\b hi there\\b0}" to the Array format ?
